const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let selected='', pickerCell=null, contextTarget=null, undo=[], redo=[], toastTimer;
const sheetText={
 account:'<p class="eyebrow">アカウント</p><h2>田中 太郎</h2><p>区域係・通常PW</p><hr><button class="sheet-link">アカウントを切り替える　›</button><button class="sheet-link">マニュアルを開く　›</button><button class="sheet-link">ログアウト　›</button>',
 applicants:'<p class="eyebrow">シフト作成</p><h2>参加希望 12名</h2><p class="sheet-note">人を選んでから、戻った作業表の配置先セルをタップできます。PCではドラッグ＆ドロップも使えます。</p><button class="sheet-person" data-person="佐藤 太郎">佐藤 太郎 <small>15:00〜18:00・責任者可</small></button><button class="sheet-person" data-person="鈴木 花子">鈴木 花子 <small>15:00〜17:00・カート不可</small></button><button class="sheet-person" data-person="高橋 一郎">高橋 一郎 <small>16:00〜18:00・カート可</small></button><button class="sheet-person" data-person="伊藤 美咲">伊藤 美咲 <small>15:00〜18:00</small></button>',
 compare:'<p class="eyebrow">シフト作成・参照モード</p><h2>別日・別時間を比較</h2><p class="sheet-note">比較側は参照専用です。閉じると、9月25日・選択中の編集位置へ戻ります。</p><div class="sheet-pills"><button class="selected" data-compare-date="9月18日">9月18日</button><button data-compare-date="10月2日">10月2日</button><button data-compare-date="10月9日">10月9日</button></div><div class="sheet-pills"><button class="selected" data-compare-time="15:00">15:00</button><button data-compare-time="16:00">16:00</button><button data-compare-time="17:00">17:00</button></div><div class="compare-card"><b data-compare-summary>9月18日 15:00</b><p>北口　田中・山田</p><p>南口　伊藤・佐藤</p><span class="status done">確認完了</span></div>',
 ai:'<p class="eyebrow">シフト作成支援</p><h2>AI原案</h2><p class="sheet-note">現在の希望、場所、検証ルールをもとに原案を作ります。実データには接続しないモックです。</p><div class="ai-rules"><b>適用ルール</b><span>責任者を優先</span><span>連続配置を警告</span><span>カート担当の重複を防止</span></div><button class="button primary" data-action="generate-ai">原案を生成</button><p class="check-result" id="ai-result"></p>',
 territory:'<p class="eyebrow">区域割り当て</p><h2>区域管理メニュー</h2><p class="sheet-note">現況を確認しながら、割当・回収・隣接・プール・グループ・バックアップへ進みます。</p><button class="sheet-link">区域一覧・割当操作　›</button><button class="sheet-link">回収待ち　<span class="status wait">3件</span></button><button class="sheet-link">隣接関係　›</button><button class="sheet-link">プール／グループ管理　›</button><button class="sheet-link">バックアップ　›</button>',
 message:'<p class="eyebrow">ログイン救済</p><h2>ログインできません</h2><p class="sheet-note">山田 花子・9月14日 9:32</p><p>Googleアカウントを変更したところ、ログインできなくなりました。</p><button class="button primary" data-action="resolve-message">救済設定を開く</button>'
};
const homeSchedule={
 '2026-09-04':{status:'申込受付',statusClass:'current',time:'—',applications:'受付開始',places:'—',note:'この日から9月分の希望受付が始まります。',primaryLabel:'日程を確認',primaryPage:'monthly',primaryTab:'schedule',secondaryLabel:'申込状況を見る',secondaryPage:'monthly',secondaryTab:'wishes'},
 '2026-09-11':{status:'公開済み',statusClass:'done',time:'15:00〜18:00',applications:'32 / 32',places:'北口・南口',note:'公開済みのシフトを確認できます。',primaryLabel:'シフトを見る',primaryPage:'monthly',primaryTab:'shifts',secondaryLabel:'申込を見る',secondaryPage:'monthly',secondaryTab:'wishes'},
 '2026-09-18':{status:'確認待ち',statusClass:'wait',time:'15:00〜18:00',applications:'30 / 32',places:'北口・南口',note:'作成済みシフトを確認者へ回しています。',primaryLabel:'シフトを確認',primaryPage:'monthly',primaryTab:'shifts',secondaryLabel:'申込を見る',secondaryPage:'monthly',secondaryTab:'wishes'},
 '2026-09-20':{status:'公開予定',statusClass:'wait',time:'—',applications:'—',places:'—',note:'確認完了したシフトの公開予定日です。',primaryLabel:'公開条件を見る',primaryPage:'monthly',primaryTab:'shifts',secondaryLabel:'日程を確認',secondaryPage:'monthly',secondaryTab:'schedule'},
 '2026-09-25':{status:'シフト作成中',statusClass:'current',time:'15:00〜18:00',applications:'28 / 32',places:'北口・南口',note:'希望を確認しながらシフトを作成しています。',primaryLabel:'シフト作成を続ける',primaryPage:'shift',secondaryLabel:'申込を見る',secondaryPage:'monthly',secondaryTab:'wishes'}
};
const defaultHomeDay={status:'予定なし',statusClass:'wait',time:'—',applications:'—',places:'—',note:'この日はPWの予定がありません。月次の日程から設定を確認できます。',primaryLabel:'日程を詳しく見る',primaryPage:'monthly',primaryTab:'schedule',secondaryLabel:'月次運用を開く',secondaryPage:'monthly'};
function showView(name){$$('[data-view]').forEach(p=>p.classList.toggle('active',p.dataset.view===name));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$('#main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});closeOverlays()}
function homeDateLabel(key){const [year,month,day]=key.split('-').map(Number);return `${month}月${day}日（${'日月火水木金土'[new Date(year,month-1,day).getDay()]}）`}
function selectHomeDate(key){const data={...defaultHomeDay,...(homeSchedule[key]||{})};$$('[data-home-date]').forEach(day=>{const active=day.dataset.homeDate===key;day.classList.toggle('selected',active);day.setAttribute('aria-pressed',String(active))});$('#home-date-title').textContent=homeDateLabel(key);const status=$('#home-date-status');status.textContent=data.status;status.className=`status ${data.statusClass}`;$('#home-date-time').textContent=data.time;$('#home-date-applications').textContent=data.applications;$('#home-date-places').textContent=data.places;$('#home-date-note').textContent=data.note;const primary=$('#home-primary-action'),secondary=$('#home-secondary-action');$('#home-primary-label').textContent=data.primaryLabel;primary.dataset.page=data.primaryPage;if(data.primaryTab)primary.dataset.monthTab=data.primaryTab;else delete primary.dataset.monthTab;$('#home-secondary-label').textContent=data.secondaryLabel;secondary.dataset.page=data.secondaryPage;if(data.secondaryTab)secondary.dataset.monthTab=data.secondaryTab;else delete secondary.dataset.monthTab;notify(`${homeDateLabel(key)}を選択しました`)}
function openSheet(type){$('#sheet-content').innerHTML=sheetText[type]||sheetText.account;$('#sheet').classList.add('open');$('#sheet').setAttribute('aria-hidden','false');$('#scrim').classList.add('open');$('#sheet').dataset.type=type}
function closeSheet(){$('#sheet').classList.remove('open');$('#sheet').setAttribute('aria-hidden','true');$('#scrim').classList.remove('open')}
function openDialog(kind){$('#dialog-title').textContent=kind==='schedule'?'予定表の確認・承認':kind==='publish'?'公開条件と公開予定':'3件の確認があります';$('#dialog').classList.add('open');$('#dialog').setAttribute('aria-hidden','false')}
function closeDialog(){$('#dialog').classList.remove('open');$('#dialog').setAttribute('aria-hidden','true')}
function closeOverlays(){closeSheet();closeDialog();$('#picker').classList.remove('open');$('#context-menu').classList.remove('open');}
function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function setMonthTab(tab){$$('[data-month-tab]').forEach(b=>b.classList.toggle('active',b.dataset.monthTab===tab));$$('[data-month-view]').forEach(v=>v.classList.toggle('active',v.dataset.monthView===tab))}
function boardSnapshot(){return $$('.cell').map(c=>[c.dataset.cell,c.dataset.personName||''])}
function restoreBoard(state){state.forEach(([id,name])=>{const c=document.querySelector(`[data-cell="${id}"]`);if(c){c.dataset.personName=name;c.classList.toggle('empty',!name);c.querySelector('.cell-person').textContent=name||'＋ 割り当て'}})}
function saveBoard(){const s=$('#save-state'),m=$('#board-message');s.textContent='● 保存中…';s.classList.add('pending');m.textContent='自動保存キューに追加しました';setTimeout(()=>{s.textContent='● 保存済み';s.classList.remove('pending');m.textContent='変更は自動保存されました'},500)}
function assign(cell,name){const old=cell.dataset.personName||'';if(old!==name)undo.push(boardSnapshot());cell.dataset.personName=name;cell.classList.toggle('empty',!name);cell.querySelector('.cell-person').textContent=name||'＋ 割り当て';if(old!==name){redo=[];saveBoard();notify(name?`${name}を配置しました`:'配置を外しました')}}
function selectPerson(name){selected=name;$$('.person,.sheet-person').forEach(p=>p.classList.toggle('selected',p.dataset.person===name));$('#selected-person').textContent=`選択中：${name}　→ 配置先セルをタップ`;notify(`${name}を選択。配置先をタップしてください`);if($('#sheet').classList.contains('open'))closeSheet()}
function openPicker(cell){pickerCell=cell;$('#picker').classList.add('open');$('#picker').setAttribute('aria-hidden','false')}
function changeContext(value){if(contextTarget){contextTarget.textContent=value+'⌄';}$('#context-menu').classList.remove('open');notify(`表示コンテキストを${value}に変更（モック）`)}
document.addEventListener('click',e=>{
 const page=e.target.closest('[data-page]');if(page){e.preventDefault();showView(page.dataset.page);if(page.dataset.monthTab){setMonthTab(page.dataset.monthTab)}return}
 const mt=e.target.closest('[data-month-tab]');if(mt){setMonthTab(mt.dataset.monthTab);return}
 const homeDate=e.target.closest('[data-home-date]');if(homeDate){selectHomeDate(homeDate.dataset.homeDate);return}
 const open=e.target.closest('[data-open-sheet]');if(open){openSheet(open.dataset.openSheet);return}
 if(e.target.closest('[data-close]')){closeOverlays();return}
 const ctx=e.target.closest('[data-context]');if(ctx){contextTarget=ctx;$('#context-menu').classList.toggle('open');$('#context-title').textContent=ctx.dataset.context==='pw'?'PWを選択':'年月を選択';return}
 const cv=e.target.closest('[data-context-value]');if(cv){changeContext(cv.dataset.contextValue);return}
 const split=e.target.closest('[data-split]');if(split){const active=$('#shift-shell').classList.toggle('split');split.textContent=active?'希望と作成の分割を解除':'希望と作成を分割';notify(active?'希望確認と作成表を分割しました':'分割表示を閉じました');return}
 const shiftDate=e.target.closest('[data-shift-date]');if(shiftDate){$$('[data-shift-date]').forEach(b=>b.classList.toggle('selected',b===shiftDate));notify(`編集対象を${shiftDate.dataset.shiftDate}に切り替えました（モック）`);return}
 const shiftTime=e.target.closest('[data-shift-time]');if(shiftTime){$$('[data-shift-time]').forEach(b=>b.classList.toggle('selected',b===shiftTime));$$('.assign-row').forEach(row=>row.classList.toggle('focused',row.dataset.time===shiftTime.dataset.shiftTime));document.querySelector(`[data-time="${shiftTime.dataset.shiftTime}"]`)?.scrollIntoView({block:'nearest'});notify(`時間帯を${shiftTime.dataset.shiftTime}に切り替えました（モック）`);return}
 const compareDate=e.target.closest('[data-compare-date]');if(compareDate){const root=compareDate.closest('.compare-panel,.sheet');root.querySelectorAll('[data-compare-date]').forEach(b=>b.classList.toggle('active',b===compareDate));root.querySelector('[data-compare-summary]').textContent=`${compareDate.dataset.compareDate} ${root.querySelector('[data-compare-time].active')?.dataset.compareTime||'15:00'}`;notify(`比較対象を${compareDate.dataset.compareDate}に変更しました`);return}
 const compareTime=e.target.closest('[data-compare-time]');if(compareTime){const root=compareTime.closest('.compare-panel,.sheet');root.querySelectorAll('[data-compare-time]').forEach(b=>b.classList.toggle('active',b===compareTime));root.querySelector('[data-compare-summary]').textContent=`${root.querySelector('[data-compare-date].active')?.dataset.compareDate||'9月18日'} ${compareTime.dataset.compareTime}`;notify(`比較時間を${compareTime.dataset.compareTime}に変更しました`);return}
 const compare=e.target.closest('[data-compare-toggle]');if(compare){if(innerWidth<761)openSheet('compare');else{$('#compare-panel').classList.toggle('open');$('#shift-shell').classList.toggle('has-compare',$('#compare-panel').classList.contains('open'));}return}
 const applicant=e.target.closest('[data-person]');if(applicant){selectPerson(applicant.dataset.person);return}
 const cart=e.target.closest('[data-cart]');if(cart){cart.textContent=cart.textContent.includes('5')?'カート 8':'カート 5';saveBoard();notify('カート担当を更新しました');return}
 const cell=e.target.closest('[data-cell]');if(cell){if(selected){assign(cell,selected);selected='';$('#selected-person').textContent='未選択：人を選んでから配置先をタップできます'}else openPicker(cell);return}
 const pv=e.target.closest('[data-picker-value]');if(pv&&pickerCell){assign(pickerCell,pv.dataset.pickerValue==='空欄にする'?'':pv.dataset.pickerValue);pickerCell=null;$('#picker').classList.remove('open');return}
 const dialog=e.target.closest('[data-dialog]');if(dialog){openDialog(dialog.dataset.dialog);return}
 const action=e.target.closest('[data-action]');if(action){runAction(action.dataset.action);return}
 if(!e.target.closest('#picker,#context-menu')){$('#picker').classList.remove('open');$('#context-menu').classList.remove('open')}
});
function runAction(action){
 if(action==='run-check'){$('#check-result').textContent='検証完了：警告1件を確認してください。公開前チェックは保存されました。';notify('検証結果を更新しました');return}
 if(action==='complete-shift'){$('#publish-state').textContent='確認待ち';$('#check-result').textContent='作成完了を登録しました。確認者2名の確認後に公開できます。';notify('シフト作成完了を登録しました');return}
 if(action==='publish'){$('#publish-state').textContent='公開待ち';$('#check-result').textContent='公開条件を確認しました。確認者2名の確認後に公開できます。';notify('公開条件を確認しました');return}
 if(action==='generate-ai'){$('#ai-result').textContent='原案を生成しました：12名を配置、警告1件。差分を確認して反映できます。';notify('AI原案を生成しました（モック）');return}
 if(action==='resolve-message'){notify('救済設定を開きます（モック）');closeSheet();return}
 if(action==='undo'){if(!undo.length){notify('元に戻せる変更はありません');return}redo.push(boardSnapshot());restoreBoard(undo.pop());saveBoard();notify('直前の配置を元に戻しました');return}
 if(action==='redo'){if(!redo.length){notify('やり直せる変更はありません');return}undo.push(boardSnapshot());restoreBoard(redo.pop());saveBoard();notify('配置をやり直しました')}
}
$$('.person').forEach(p=>{p.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',p.dataset.person);selected=p.dataset.person;notify(`${selected}をドラッグ中。セルへドロップできます`)});});
$$('.cell').forEach(c=>{c.addEventListener('dragover',e=>{e.preventDefault();c.classList.add('drop-target')});c.addEventListener('dragleave',()=>c.classList.remove('drop-target'));c.addEventListener('drop',e=>{e.preventDefault();c.classList.remove('drop-target');assign(c,e.dataTransfer.getData('text/plain'));selected=''})});
$('#scrim').addEventListener('click',closeOverlays);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOverlays()});
